import { LucideIcon, User, Book, ChartPie, Share2, Users } from "lucide-react";

export interface Field {
  title: string;
  category:
    | "text"
    | "number"
    | "date"
    | "dropdown"
    | "email"
    | "text"
    | "multiselect"
    | "textarea"
    | "file"
    | "range";
  slug: string;
  options?: string[];
  dependsOn?: string;
  placeholder?: string;
}

interface Step {
  title?: string;
  description?: string;
  icon: LucideIcon;
  fields: Field[];
}

interface Questions {
  [key: string]: Step;
}

export const CREATOR_QUESTIONS: Questions = {
  step1: {
    title: "Your Profile",
    icon: User,
    description: "Tell us a bit about yourself.",
    fields: [
      {
        title: "Do you consider yourself a UGC creator or an Influencer?",
        slug: "are-you-ugc-creator",
        category: "dropdown",
        options: ["Influencer", "UGC"],
        placeholder: "Select your creator type",
      },
      {
        title: "What's your full name?",
        slug: "full-name",
        category: "text",
        placeholder: "Enter your full name",
      },
      {
        title: "Do you have preferred name?",
        slug: "stage-name",
        category: "text",
        placeholder: "Enter your preferred name (optional)",
      },
      {
        title: "What is your Date Of Birth?",
        slug: "dob",
        category: "date",
        placeholder: "Select your date of birth",
      },
    ],
  },
  step2: {
    title: "Your Audience",
    icon: Users,
    description: "Tell us a bit about your audience.",
    fields: [
      {
        title: "Choose Your Gender",
        slug: "gender",
        category: "dropdown",
        options: ["Male", "Female", "Non-binary", "Prefer not to say"],
        placeholder: "Select your gender",
      },
      {
        title: "What country do you operate out of?",
        slug: "country",
        category: "dropdown",
        options: [
          "Australia",
          "Brazil",
          "Canada",
          "China",
          "France",
          "Germany",
          "India",
          "Italy",
          "Japan",
          "Mexico",
          "Netherlands",
          "Russia",
          "Saudi Arabia",
          "South Korea",
          "Spain",
          "Sweden",
          "Switzerland",
          "Turkey",
          "United Kingdom",
          "United States",
        ],
        placeholder: "Select your country",
      },
      {
        title: "What languages do you speak?",
        slug: "language",
        category: "multiselect",
        options: [
          "English",
          "Spanish",
          "French",
          "German",
          "Japanese",
          "Chinese",
          "Hindi",
          "Arabic",
          "Portuguese",
          "Russian",
          "Italian",
          "Korean",
          "Turkish",
          "Dutch",
          "Polish",
          "Swedish",
          "Greek",
          "Hebrew",
          "Thai",
          "Vietnamese",
          "Czech",
          "Hungarian",
          "Bengali",
          "Urdu",
          "Malay",
          "Persian",
          "Romanian",
          "Tagalog",
          "Indonesian",
          "Tamil",
          "Telugu",
          "Marathi",
          "Punjabi",
          "Ukrainian",
          "Finnish",
          "Danish",
          "Norwegian",
          "Serbian",
          "Slovak",
          "Croatian",
          "Bulgarian",
          "Lithuanian",
          "Latvian",
          "Estonian",
          "Slovenian",
          "Basque",
          "Catalan",
          "Galician",
          "Macedonian",
          "Albanian",
          "Maltese",
          "Swahili",
          "Hausa",
          "Yoruba",
          "Igbo",
          "Afrikaans",
        ],
        placeholder: "Select languages (max 3)",
      },
      {
        title: "What is primary niche?",
        slug: "primary-niche",
        category: "multiselect",
        options: [
          "Beauty & Care",
          "Business & Finance",
          "Events",
          "Fashion & Style",
          "Food & Drinks",
          "Foodie",
          "Gaming",
          "Hair",
          "Health & Wellness",
          "Homemade",
          "Home & Garden",
          "Jewellery",
          "Kids & Parenting",
          "Lifestyle",
          "Makeup",
          "Music",
          "Nutrition",
          "Outdoors & Nature",
          "Pet",
          "Photography",
          "Restaurants",
          "Skincare",
          "Sports & Fitness",
          "Tech",
          "Travel",
          "Yoga",
          "Others",
        ],
        placeholder: "Select your primary niche",
      },
    ],
  },

  step3: {
    title: "About Yourself",
    icon: User,
    description: "Tell us a bit about your social media presence.",
    fields: [
      {
        title: "Tell Us About Yourself",
        slug: "tell-us-about-yourself",
        category: "textarea",
        placeholder:
          "Share a brief intro about yourself, your content style, active social platforms, audience demographics, and what you’re looking for in brand collaborations.",
      },
    ],
  },

  step4: {
    title: "Your Social Media",
    icon: Share2,
    description: "Tell us a bit about your social media presence.",
    fields: [
      {
        title: "What primary social media platform you operate from ?",
        slug: "primary-social-media",
        category: "dropdown",
        options: [
          "Facebook",
          "Instagram",
          "LinkedIn",
          "Newsletter",
          "Pinterest",
          "TikTok",
          "Twitch",
          "Twitter / X",
          "Youtube",
          "Youtube Reel",
        ],
        placeholder: "Select primary platform",
      },
      {
        title: "Enter your primary social media profile link",
        slug: "primary-social-media-link",
        category: "text",
        dependsOn: "primary-social-media",
        placeholder: "Enter your profile URL",
      },
      {
        title: "How many followers do you have on your primary social media?",
        slug: "primary-followers",
        category: "dropdown",
        options: [
          "Less than 1,000",
          "1,000 - 10,000",
          "10,000 - 100,000",
          "100,000 - 1,000,000",
          "More than 1,000,000",
        ],
        placeholder: "Select follower count",
      },
      {
        title: "What social media platforms do you operate from 2nd most?",
        slug: "secondary-social-media",
        category: "dropdown",
        options: [
          "Facebook",
          "Instagram",
          "LinkedIn",
          "Newsletter",
          "Pinterest",
          "TikTok",
          "Twitch",
          "Twitter / X",
          "Youtube",
          "Youtube Reel",
        ],
        placeholder: "Select secondary platform (optional)",
      },
      {
        title: "Enter your secondary social media profile link",
        slug: "secondary-social-media-link",
        category: "text",
        dependsOn: "secondary-social-media",
        placeholder: "Enter your profile URL",
      },
      {
        title: "How many followers do you have on your secondary social media?",
        slug: "secondary-followers",
        category: "dropdown",
        options: [
          "Less than 1,000",
          "1,000 - 10,000",
          "10,000 - 100,000",
          "100,000 - 1,000,000",
          "More than 1,000,000",
        ],
        placeholder: "Select follower count",
      },
    ],
  },

  step5: {
    title: "Audience Details",
    icon: User,
    description: "",
    fields: [
      {
        title: "Primary Audience Location",
        slug: "primary-audience-location",
        category: "dropdown",
        options: [
          "Australia",
          "Brazil",
          "Canada",
          "China",
          "France",
          "Germany",
          "India",
          "Italy",
          "Japan",
          "Mexico",
          "Netherlands",
          "Russia",
          "Saudi Arabia",
          "South Korea",
          "Spain",
          "Sweden",
          "Switzerland",
          "Turkey",
          "United Kingdom",
          "United States",
        ],
        placeholder: "Location",
      },
      {
        title: "Primary Audience Gender",
        slug: "primary-audience-gender",
        category: "dropdown",
        options: [
          "Male",
          "Female",
          "Non-binary",
          "Prefer not to say",
        ],
        placeholder: "Gender",
      },
      {
        title: "Primary Audience Gender (Others)",
        slug: "primary-audience-gender-other",
        category: "text",
        placeholder: "Gender",
        dependsOn: "primary-audience-gender",
      },
      {
        title: "Primary Audience Age",
        slug: "primary-audience-age",
        category: "dropdown",
        options: ["<18", "18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
        placeholder: "Age group",
      },
      {
        title: "Primary Audience Percentage",
        slug: "primary-audience-percentage",
        category: "dropdown",
        options: [
          "0-10%",
          "10-20%",
          "20-30%",
          "30-40%",
          "40-50%",
          "50-60%",
          "60-70%",
          "70-80%",
          "80-90%",
          "90-100%",
        ],
        placeholder: "Audience percentage",
      },
      {
        title: "Secondary Audience Location",
        slug: "secondary-audience-location",
        category: "dropdown",
        options: [
          "Australia",
          "Brazil",
          "Canada",
          "China",
          "France",
          "Germany",
          "India",
          "Italy",
          "Japan",
          "Mexico",
          "Netherlands",
          "Russia",
          "Saudi Arabia",
          "South Korea",
          "Spain",
          "Sweden",
          "Switzerland",
          "Turkey",
          "United Kingdom",
          "United States",
        ],
        placeholder: "Location",
      },
      {
        title: "Secondary Audience Gender",
        slug: "secondary-audience-gender",
        category: "dropdown",
        options: [
          "Male",
          "Female",
          "Non-binary",
          "Prefer not to say",
        ],
        placeholder: "Audience gender",
      },
      {
        title: "Secondary Audience Gender (Others)",
        slug: "secondary-audience-gender-other",
        category: "text",
        placeholder: "Audience gender",
        dependsOn: "secondary-audience-gender",
      },
      {
        title: "Secondary Audience Age",
        slug: "secondary-audience-age",
        category: "dropdown",
        options: ["<18", "18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
        placeholder: "Age group",
      },
      {
        title: "Secondary Audience Percentage",
        slug: "secondary-audience-percentage",
        category: "dropdown",
        options: [
          "0-10%",
          "10-20%",
          "20-30%",
          "30-40%",
          "40-50%",
          "50-60%",
          "60-70%",
          "70-80%",
          "80-90%",
          "90-100%",
        ],
        placeholder: "Audience percentage",
      },
    ],
  },

  step6: {
    title: "Audience Insights",
    icon: ChartPie,
    description: "Tell us a bit about your audience.",
    fields: [
      {
        title: "What's the growth rate of your followers over last six months?",
        slug: "growth-rate",
        category: "dropdown",
        options: [
          "Less than 10%",
          "10% - 20%",
          "20% - 30%",
          "30% - 40%",
          "40% - 50%",
          "50% - 60%",
          "60% - 70%",
          "70% - 80%",
          "80% - 90%",
          "90% - 100%",
          "More than 100%",
        ],
        placeholder: "Select growth rate",
      },
      {
        title: "What are the top three geographic locations of your audience?",
        slug: "primary-locations",
        category: "multiselect",
        options: [
          "Australia",
          "Brazil",
          "Canada",
          "China",
          "France",
          "Germany",
          "India",
          "Italy",
          "Japan",
          "Mexico",
          "Netherlands",
          "Russia",
          "Saudi Arabia",
          "South Korea",
          "Spain",
          "Sweden",
          "Switzerland",
          "Turkey",
          "United Kingdom",
          "United States",
        ],
        placeholder: "Select top 3 locations",
      },
      {
        title: "What % of your audience is US based?",
        slug: "us-based-audience",
        category: "dropdown",
        options: [
          "Less than 10%",
          "10% - 20%",
          "20% - 30%",
          "30% - 40%",
          "40% - 50%",
          "50% - 60%",
          "60% - 70%",
          "70% - 80%",
          "80% - 90%",
          "90% - 100%",
          "More than 100%",
        ],
        placeholder: "Select US audience percentage",
      },
    ],
  },

  step7: {
    title: "Content and Engagement",
    icon: Book,
    description: "Tell us a bit about your content and engagement.",
    fields: [
      {
        title: "What age bracket follows you the most?",
        slug: "top-two-audiences",
        category: "multiselect",
        options: ["< 18", "18-24", "25-34", "35-44", "45-54", "55+"],
        placeholder: "Select top age brackets",
      },
      {
        title: "What are the average views of your last 8 reels?",
        slug: "average-views",
        category: "dropdown",
        options: [
          "Less than 1,000",
          "1,000 - 10,000",
          "10,000 - 100,000",
          "100,000 - 1,000,000",
          "More than 1,000,000",
        ],
        placeholder: "Select average views",
      },
      {
        title: "What are your favourite brands?",
        slug: "favourite-brands",
        category: "text",
        placeholder: "Enter your favorite brands",
      },
      {
        title: "Have you worked with AI consumer apps before?",
        slug: "worked-with-ai",
        category: "dropdown",
        options: ["Yes", "No"],
        placeholder: "Select",
      },
      {
        title: "Do you have any experience in paid campaigns?",
        slug: "paid-campaigns",
        category: "dropdown",
        options: ["Yes", "No", "Gifted", "Affiliate Marketing", "Other"],
        placeholder: "Select",
      },
      {
        title: "What’s Your desired compensation per video ?",
        slug: "budget-video",
        category: "range",
        placeholder: "Enter your desired compensation per video",
        options: [
          "$1 - $100",
          "$100 - $200",
          "$200 - $450",
          "$451 - $1000",
          "$1000 - $2000",
          "$2000+",
        ],
      },
    ],
  },
};
